using System.Collections.ObjectModel;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using HaPlay.Models;
using HaPlay.Resources;
using S.Media.Source.YouTube;

namespace HaPlay.ViewModels.Dialogs;

/// <summary>One selectable video stream row (muxed streams are rarely offered — video is its own leg).</summary>
public sealed record YouTubeVideoOption(YouTubeVideoStreamInfo Info)
{
    public override string ToString() =>
        $"{Info.QualityLabel} · {Info.Codec} · {Info.Container} · {Info.SizeBytes / (1024.0 * 1024.0):F1} MiB";
}

/// <summary>One selectable audio stream row (audio comes in separately from video).</summary>
public sealed record YouTubeAudioOption(YouTubeAudioStreamInfo Info)
{
    public override string ToString() =>
        $"{Info.Codec} · {Info.Container} · {Info.BitrateBps / 1000} kbps" +
        (Info.Language is { Length: > 0 } l ? $" · {l}{(Info.IsDefaultLanguage ? " (default)" : "")}" : "");
}

/// <summary>One selectable caption track row; a null <see cref="Info"/> is the "(no subtitles)" entry.</summary>
public sealed record YouTubeSubtitleOption(YouTubeCaptionTrackInfo? Info)
{
    public override string ToString() => Info is null
        ? Strings.YouTubeNoSubtitlesOption
        : $"{Info.LanguageName} ({Info.LanguageCode}){(Info.IsAutoGenerated ? " · auto" : "")}";
}

/// <summary>
/// Add/edit dialog for a YouTube source (deck playlist AND cue player share it): paste a URL → resolve
/// the stream manifest → pick the video stream, audio stream and subtitle track → download the selected
/// streams into the local cache (remuxed to one asset) → produce the <see cref="YouTubePlaylistItem"/>
/// carrying the RESOLVED descriptors. Reliable mode means caching here is what makes GO instant later.
/// </summary>
public sealed partial class AddYouTubeDialogViewModel : ObservableObject
{
    private readonly IYouTubeGateway _gateway;
    private readonly YouTubePreparer _preparer;
    private YouTubeMediaManifest? _manifest;
    private YouTubePlaylistItem? _existing;
    private CancellationTokenSource? _cts;

    public AddYouTubeDialogViewModel(IYouTubeGateway? gateway = null, YouTubePreparer? preparer = null)
    {
        _gateway = gateway ?? Playback.YouTubeRuntime.Gateway;
        _preparer = preparer ?? Playback.YouTubeRuntime.Preparer;
    }

    public string DialogTitle => _existing is null
        ? Strings.AddYouTubeDialogTitle
        : Strings.EditYouTubeDialogTitle;

    public string PrimaryButtonLabel => Strings.YouTubeDownloadAndAddButton;

    [ObservableProperty] private string _url = string.Empty;
    [ObservableProperty] private string? _validationMessage;
    [ObservableProperty] private bool _isResolving;
    [ObservableProperty] private bool _isPreparing;
    [ObservableProperty] private string? _videoTitle;
    [ObservableProperty] private string? _videoAuthor;
    [ObservableProperty] private string? _videoDurationText;
    [ObservableProperty] private bool _hasManifest;
    [ObservableProperty] private bool _audioOnly;
    [ObservableProperty] private double _prepareProgress;
    [ObservableProperty] private string? _prepareStatus;
    [ObservableProperty] private string? _prepareDetail;
    [ObservableProperty] private string? _cacheStatus;

    // Rolling download-speed sample: baseline (bytes, time) within the current phase; speed is the
    // delta over ≥0.5 s windows so the readout doesn't flicker with every progress callback.
    private YouTubePreparePhase _speedPhase;
    private long _speedBaselineBytes;
    private long _speedBaselineTimestamp;
    private double _speedBytesPerSecond;

    public ObservableCollection<YouTubeVideoOption> VideoStreams { get; } = new();
    public ObservableCollection<YouTubeAudioOption> AudioStreams { get; } = new();
    public ObservableCollection<YouTubeSubtitleOption> SubtitleTracks { get; } = new();

    [ObservableProperty] private YouTubeVideoOption? _selectedVideoStream;
    [ObservableProperty] private YouTubeAudioOption? _selectedAudioStream;
    [ObservableProperty] private YouTubeSubtitleOption? _selectedSubtitleTrack;

    /// <summary>Raised with the finished item once the selected streams are cached; the view closes on it.</summary>
    public event Action<YouTubePlaylistItem>? Completed;

    partial void OnSelectedVideoStreamChanged(YouTubeVideoOption? value) => RefreshCacheStatus();
    partial void OnSelectedAudioStreamChanged(YouTubeAudioOption? value) => RefreshCacheStatus();
    partial void OnAudioOnlyChanged(bool value) => RefreshCacheStatus();

    /// <summary>Pre-populates edit mode: the item's canonical URL, then a resolve re-selects its streams.</summary>
    public void LoadFromExisting(YouTubePlaylistItem item)
    {
        _existing = item;
        Url = Playback.HaPlayPlaybackHelpers.BuildYouTubeUri(item);
        AudioOnly = item.AudioOnly;
        OnPropertyChanged(nameof(DialogTitle));
    }

    [RelayCommand]
    private async Task ResolveAsync()
    {
        ValidationMessage = null;
        if (!YouTubeSourceUri.TryParse(Url?.Trim(), out var videoId, out var uriSelection))
        {
            ValidationMessage = Strings.YouTubeUrlNotRecognized;
            return;
        }

        _cts?.Cancel();
        _cts = new CancellationTokenSource();
        IsResolving = true;
        try
        {
            _manifest = await _gateway.GetManifestAsync(videoId, _cts.Token);
            VideoTitle = _manifest.Title;
            VideoAuthor = _manifest.Author;
            VideoDurationText = _manifest.Duration is { } d ? d.ToString(@"hh\:mm\:ss") : null;

            VideoStreams.Clear();
            foreach (var v in _manifest.VideoStreams)
                VideoStreams.Add(new YouTubeVideoOption(v));
            AudioStreams.Clear();
            foreach (var a in _manifest.AudioStreams)
                AudioStreams.Add(new YouTubeAudioOption(a));
            SubtitleTracks.Clear();
            SubtitleTracks.Add(new YouTubeSubtitleOption(null));
            foreach (var c in _manifest.CaptionTracks)
                SubtitleTracks.Add(new YouTubeSubtitleOption(c));

            // Preselect: the edited item's persisted streams (or the URI's), else best-by-policy defaults.
            var wantVideo = _existing?.VideoStreamDescriptor ?? uriSelection.Video;
            var wantAudio = _existing?.AudioStreamDescriptor ?? uriSelection.Audio;
            var wantSub = _existing?.SubtitleLanguage ?? uriSelection.SubtitleLanguage;
            SelectedVideoStream =
                VideoStreams.FirstOrDefault(o => o.Info.Descriptor == wantVideo) ?? VideoStreams.FirstOrDefault();
            SelectedAudioStream =
                AudioStreams.FirstOrDefault(o => o.Info.Descriptor == wantAudio)
                ?? AudioStreams.FirstOrDefault(o => o.Info.IsDefaultLanguage)
                ?? AudioStreams.FirstOrDefault();
            SelectedSubtitleTrack =
                SubtitleTracks.FirstOrDefault(o => o.Info is not null && o.Info.LanguageCode == wantSub)
                ?? SubtitleTracks[0];
            HasManifest = true;
            RefreshCacheStatus();
        }
        catch (OperationCanceledException)
        {
            // superseded by a newer resolve / dialog close
        }
        catch (Exception ex)
        {
            // Show the actual provider error — the app must not promise every URL is playable.
            ValidationMessage = Strings.Format(nameof(Strings.YouTubeResolveFailedFormat), ex.Message);
            HasManifest = false;
        }
        finally
        {
            IsResolving = false;
        }
    }

    [RelayCommand]
    private async Task PrepareAndAcceptAsync()
    {
        ValidationMessage = null;
        if (_manifest is null)
        {
            ValidationMessage = Strings.YouTubeResolveFirstHint;
            return;
        }

        if (!AudioOnly && SelectedVideoStream is null)
        {
            ValidationMessage = Strings.YouTubeSelectVideoStreamHint;
            return;
        }

        var selection = new YouTubeStreamSelection(
            AudioOnly ? null : SelectedVideoStream?.Info.Descriptor,
            SelectedAudioStream?.Info.Descriptor,
            SelectedSubtitleTrack?.Info?.LanguageCode)
        {
            IncludeVideo = !AudioOnly,
        };

        _cts?.Cancel();
        _cts = new CancellationTokenSource();
        IsPreparing = true;
        PrepareProgress = 0;
        PrepareDetail = null;
        _speedPhase = YouTubePreparePhase.Resolving;
        _speedBytesPerSecond = 0;
        try
        {
            var prepared = await _preparer.PrepareAsync(
                _manifest.VideoId, selection,
                new Progress<YouTubePrepareProgress>(p =>
                {
                    PrepareProgress = p.Fraction;
                    PrepareStatus = p.Phase switch
                    {
                        YouTubePreparePhase.Resolving => Strings.YouTubePhaseResolving,
                        YouTubePreparePhase.DownloadingVideo => Strings.YouTubePhaseDownloadingVideo,
                        YouTubePreparePhase.DownloadingAudio => Strings.YouTubePhaseDownloadingAudio,
                        YouTubePreparePhase.Remuxing => Strings.YouTubePhaseRemuxing,
                        _ => Strings.YouTubePhaseReady,
                    };
                    PrepareDetail = BuildDownloadDetail(p);
                }),
                _cts.Token);

            var item = new YouTubePlaylistItem(_manifest.VideoId)
            {
                Id = _existing?.Id ?? Guid.NewGuid(),
                Title = _manifest.Title,
                Author = _manifest.Author,
                DurationSeconds = _manifest.Duration?.TotalSeconds,
                VideoStreamDescriptor = prepared.ResolvedSelection.Video,
                AudioStreamDescriptor = prepared.ResolvedSelection.Audio,
                SubtitleLanguage = prepared.SubtitlePath is null ? null : prepared.ResolvedSelection.SubtitleLanguage,
                AudioOnly = AudioOnly,
                Subtitles = prepared.SubtitlePath is null
                    ? []
                    : [new CueSubtitleSelection
                    {
                        Path = prepared.SubtitlePath,
                        Label = SelectedSubtitleTrack?.Info?.LanguageName ?? prepared.ResolvedSelection.SubtitleLanguage,
                    }],
            };
            Completed?.Invoke(item);
        }
        catch (OperationCanceledException)
        {
            PrepareStatus = null;
        }
        catch (Exception ex)
        {
            ValidationMessage = Strings.Format(nameof(Strings.YouTubePrepareFailedFormat), ex.Message);
        }
        finally
        {
            IsPreparing = false;
        }
    }

    /// <summary>Cancels an in-flight resolve/prepare (dialog cancel/close).</summary>
    public void CancelPending() => _cts?.Cancel();

    /// <summary>Byte-level readout for the download phases: "done / total · speed". The gateway reports a
    /// 0–1 fraction and the manifest carries each stream's exact size, so bytes are derived here — the
    /// currently-downloading stream is identified by the phase. Non-download phases show no detail.</summary>
    private string? BuildDownloadDetail(YouTubePrepareProgress p)
    {
        var total = p.Phase switch
        {
            YouTubePreparePhase.DownloadingVideo => SelectedVideoStream?.Info.SizeBytes ?? 0,
            YouTubePreparePhase.DownloadingAudio => SelectedAudioStream?.Info.SizeBytes ?? 0,
            _ => 0,
        };
        if (total <= 0)
            return null;

        var done = (long)(p.Fraction * total);

        // Speed over ≥0.5 s windows within one phase (a phase switch restarts the byte counter).
        var now = Environment.TickCount64;
        if (p.Phase != _speedPhase)
        {
            _speedPhase = p.Phase;
            _speedBaselineBytes = done;
            _speedBaselineTimestamp = now;
            _speedBytesPerSecond = 0;
        }
        else if (now - _speedBaselineTimestamp >= 500)
        {
            var seconds = (now - _speedBaselineTimestamp) / 1000.0;
            _speedBytesPerSecond = (done - _speedBaselineBytes) / seconds;
            _speedBaselineBytes = done;
            _speedBaselineTimestamp = now;
        }

        var doneText = MediaPropertiesDialogViewModel.FormatSize(done);
        var totalText = MediaPropertiesDialogViewModel.FormatSize(total);
        return _speedBytesPerSecond > 0
            ? Strings.Format(nameof(Strings.YouTubeDownloadDetailWithSpeedFormat),
                doneText, totalText, MediaPropertiesDialogViewModel.FormatSize((long)_speedBytesPerSecond))
            : Strings.Format(nameof(Strings.YouTubeDownloadDetailFormat), doneText, totalText);
    }

    private void RefreshCacheStatus()
    {
        if (_manifest is null)
        {
            CacheStatus = null;
            return;
        }

        var cached = _preparer.IsPrepared(
            _manifest.VideoId,
            AudioOnly ? null : SelectedVideoStream?.Info.Descriptor,
            SelectedAudioStream?.Info.Descriptor);
        CacheStatus = cached ? Strings.YouTubeAlreadyCachedStatus : Strings.YouTubeNotCachedStatus;
    }
}
