using YoutubeExplode;
using YoutubeExplode.Videos;
using YoutubeExplode.Videos.ClosedCaptions;
using YoutubeExplode.Videos.Streams;

namespace S.Media.Source.YouTube;

/// <summary>One selectable video stream, described in operator terms (for the stream-picker dialogs).</summary>
public sealed record YouTubeVideoStreamInfo(
    string Descriptor, string QualityLabel, int Height, int Framerate,
    string Codec, string Container, long SizeBytes, long BitrateBps);

/// <summary>One selectable audio stream (YouTube ships audio separately from video at high quality).</summary>
public sealed record YouTubeAudioStreamInfo(
    string Descriptor, string Codec, string Container, long SizeBytes, long BitrateBps,
    string? Language, bool IsDefaultLanguage);

/// <summary>One selectable caption track.</summary>
public sealed record YouTubeCaptionTrackInfo(string LanguageCode, string LanguageName, bool IsAutoGenerated);

/// <summary>Resolved metadata + stream manifest for one video — everything the selection UI needs.</summary>
public sealed record YouTubeMediaManifest(
    string VideoId,
    string Title,
    string Author,
    TimeSpan? Duration,
    IReadOnlyList<YouTubeVideoStreamInfo> VideoStreams,
    IReadOnlyList<YouTubeAudioStreamInfo> AudioStreams,
    IReadOnlyList<YouTubeCaptionTrackInfo> CaptionTracks);

/// <summary>
/// The network seam of the module: everything that talks to YouTube goes through this interface so the
/// cache/preparer/provider logic tests offline with a fake. The real implementation wraps YoutubeExplode.
/// </summary>
public interface IYouTubeGateway
{
    Task<YouTubeMediaManifest> GetManifestAsync(string videoId, CancellationToken cancellationToken);

    /// <summary>Downloads the stream matching <paramref name="descriptor"/> (video or audio) to a file.</summary>
    Task DownloadStreamAsync(
        string videoId, string descriptor, string filePath,
        IProgress<double>? progress, CancellationToken cancellationToken);

    /// <summary>Downloads the caption track for <paramref name="languageCode"/> as SRT, or returns false when absent.</summary>
    Task<bool> TryDownloadCaptionsSrtAsync(
        string videoId, string languageCode, string filePath, CancellationToken cancellationToken);
}

/// <summary>YoutubeExplode-backed gateway. Descriptors are produced and re-matched here so the format
/// stays private to the module: video <c>label|codec|container</c>, audio <c>codec|container|language</c>.</summary>
public sealed class YoutubeExplodeGateway : IYouTubeGateway
{
    private readonly YoutubeClient _client = new();

    internal static string DescribeVideo(IVideoStreamInfo s) =>
        $"{s.VideoQuality.Label}|{s.VideoCodec}|{s.Container.Name}";

    internal static string DescribeAudio(IAudioStreamInfo s) =>
        $"{s.AudioCodec}|{s.Container.Name}|{s.AudioLanguage?.Code ?? ""}";

    public async Task<YouTubeMediaManifest> GetManifestAsync(string videoId, CancellationToken cancellationToken)
    {
        var id = VideoId.Parse(videoId);
        var video = await _client.Videos.GetAsync(id, cancellationToken).ConfigureAwait(false);
        var manifest = await _client.Videos.Streams.GetManifestAsync(id, cancellationToken).ConfigureAwait(false);

        var videoStreams = manifest.GetVideoOnlyStreams()
            .OrderByDescending(s => s.VideoQuality)
            .Select(s => new YouTubeVideoStreamInfo(
                DescribeVideo(s), s.VideoQuality.Label, s.VideoResolution.Height, s.VideoQuality.Framerate,
                s.VideoCodec, s.Container.Name, s.Size.Bytes, (long)s.Bitrate.BitsPerSecond))
            .ToList();

        var audioStreams = manifest.GetAudioOnlyStreams()
            .OrderByDescending(s => s.Bitrate)
            .Select(s => new YouTubeAudioStreamInfo(
                DescribeAudio(s), s.AudioCodec, s.Container.Name, s.Size.Bytes, (long)s.Bitrate.BitsPerSecond,
                s.AudioLanguage?.Code, s.IsAudioLanguageDefault ?? false))
            .ToList();

        var captions = new List<YouTubeCaptionTrackInfo>();
        try
        {
            var captionManifest = await _client.Videos.ClosedCaptions
                .GetManifestAsync(id, cancellationToken).ConfigureAwait(false);
            captions.AddRange(captionManifest.Tracks.Select(t =>
                new YouTubeCaptionTrackInfo(t.Language.Code, t.Language.Name, t.IsAutoGenerated)));
        }
        catch
        {
            // Captions are best-effort metadata — their absence must not block stream selection.
        }

        return new YouTubeMediaManifest(
            id.Value, video.Title, video.Author.ChannelTitle, video.Duration,
            videoStreams, audioStreams, captions);
    }

    public async Task DownloadStreamAsync(
        string videoId, string descriptor, string filePath,
        IProgress<double>? progress, CancellationToken cancellationToken)
    {
        var id = VideoId.Parse(videoId);
        var manifest = await _client.Videos.Streams.GetManifestAsync(id, cancellationToken).ConfigureAwait(false);
        IStreamInfo? stream =
            manifest.GetVideoOnlyStreams().FirstOrDefault(s => DescribeVideo(s) == descriptor)
            ?? (IStreamInfo?)manifest.GetAudioOnlyStreams().FirstOrDefault(s => DescribeAudio(s) == descriptor);
        if (stream is null)
            throw new InvalidOperationException(
                $"YouTube stream '{descriptor}' is no longer offered for video '{videoId}' — reselect streams.");

        await _client.Videos.Streams
            .DownloadAsync(stream, filePath, progress, cancellationToken).ConfigureAwait(false);
    }

    public async Task<bool> TryDownloadCaptionsSrtAsync(
        string videoId, string languageCode, string filePath, CancellationToken cancellationToken)
    {
        var id = VideoId.Parse(videoId);
        ClosedCaptionManifest captionManifest;
        try
        {
            captionManifest = await _client.Videos.ClosedCaptions
                .GetManifestAsync(id, cancellationToken).ConfigureAwait(false);
        }
        catch
        {
            return false;
        }

        var trackInfo = captionManifest.Tracks
            .FirstOrDefault(t => string.Equals(t.Language.Code, languageCode, StringComparison.OrdinalIgnoreCase));
        if (trackInfo is null)
            return false;

        var track = await _client.Videos.ClosedCaptions.GetAsync(trackInfo, cancellationToken).ConfigureAwait(false);
        await File.WriteAllTextAsync(filePath, ToSrt(track), cancellationToken).ConfigureAwait(false);
        return true;
    }

    /// <summary>Minimal SRT writer (index / HH:MM:SS,mmm --> … / text) for caption tracks.</summary>
    internal static string ToSrt(ClosedCaptionTrack track)
    {
        var sb = new System.Text.StringBuilder();
        var index = 1;
        foreach (var caption in track.Captions)
        {
            if (string.IsNullOrWhiteSpace(caption.Text))
                continue;
            var start = caption.Offset;
            var end = caption.Offset + caption.Duration;
            sb.Append(index++).AppendLine()
              .Append(Stamp(start)).Append(" --> ").Append(Stamp(end)).AppendLine()
              .AppendLine(caption.Text.Trim())
              .AppendLine();
        }

        return sb.ToString();

        static string Stamp(TimeSpan t) =>
            $"{(int)t.TotalHours:00}:{t.Minutes:00}:{t.Seconds:00},{t.Milliseconds:000}";
    }
}
