using System.Collections.Concurrent;
using Xunit;

namespace S.Media.Source.YouTube.Tests;

/// <summary>All offline: the network seam (<see cref="IYouTubeGateway"/>) is faked and the remux step is
/// injected, so URI/cache/coalescing/provider behavior is covered without YouTube or FFmpeg natives.</summary>
public sealed class YouTubeModuleTests : IDisposable
{
    private readonly string _dir = Directory.CreateTempSubdirectory("yt-cache-").FullName;

    public void Dispose()
    {
        try { Directory.Delete(_dir, recursive: true); }
        catch { /* best effort */ }
    }

    // ---- URI codec -------------------------------------------------------------------------------

    [Theory]
    [InlineData("https://www.youtube.com/watch?v=dQw4w9WgXcQ")]
    [InlineData("https://youtu.be/dQw4w9WgXcQ")]
    [InlineData("https://www.youtube.com/shorts/dQw4w9WgXcQ")]
    [InlineData("youtube://dQw4w9WgXcQ")]
    public void TryParse_NormalizesEveryUrlForm_ToTheSameVideoId(string uri)
    {
        Assert.True(YouTubeSourceUri.TryParse(uri, out var id, out _));
        Assert.Equal("dQw4w9WgXcQ", id);
    }

    [Fact]
    public void BuildAndParse_RoundTripsSelections()
    {
        var selection = new YouTubeStreamSelection(
            Video: "1080p60|avc1.64002a|mp4",
            Audio: "opus|webm|en",
            SubtitleLanguage: "de");
        var uri = YouTubeSourceUri.Build("dQw4w9WgXcQ", selection);

        Assert.True(YouTubeSourceUri.TryParse(uri, out var id, out var parsed));
        Assert.Equal("dQw4w9WgXcQ", id);
        Assert.Equal(selection, parsed);
    }

    [Fact]
    public void BuildAndParse_RoundTripsAudioOnly()
    {
        var uri = YouTubeSourceUri.Build("dQw4w9WgXcQ", new YouTubeStreamSelection { IncludeVideo = false });
        Assert.True(YouTubeSourceUri.TryParse(uri, out _, out var parsed));
        Assert.False(parsed.IncludeVideo);
    }

    [Theory]
    [InlineData("/tmp/some/file.mp4")]
    [InlineData("ndi://camera-1")]
    [InlineData("not a uri at all")]
    public void TryParse_RejectsNonYouTubeSources(string uri) =>
        Assert.False(YouTubeSourceUri.TryParse(uri, out _, out _));

    // ---- prepare / cache -------------------------------------------------------------------------

    private sealed class FakeGateway : IYouTubeGateway
    {
        public int ManifestCalls;
        public int DownloadCalls;
        public TimeSpan DownloadDelay = TimeSpan.Zero;

        public YouTubeMediaManifest Manifest { get; set; } = new(
            "dQw4w9WgXcQ", "Test Video", "Test Author", TimeSpan.FromMinutes(3),
            [
                new YouTubeVideoStreamInfo("1080p|avc1|mp4", "1080p", 1080, 30, "avc1", "mp4", 100, 1000),
                new YouTubeVideoStreamInfo("720p|avc1|mp4", "720p", 720, 30, "avc1", "mp4", 50, 500),
            ],
            [
                new YouTubeAudioStreamInfo("opus|webm|en", "opus", "webm", 10, 128, "en", IsDefaultLanguage: true),
                new YouTubeAudioStreamInfo("opus|webm|ja", "opus", "webm", 10, 128, "ja", IsDefaultLanguage: false),
            ],
            [new YouTubeCaptionTrackInfo("en", "English", IsAutoGenerated: false)]);

        public Task<YouTubeMediaManifest> GetManifestAsync(string videoId, CancellationToken ct)
        {
            Interlocked.Increment(ref ManifestCalls);
            return Task.FromResult(Manifest);
        }

        public async Task DownloadStreamAsync(
            string videoId, string descriptor, string filePath, IProgress<double>? progress, CancellationToken ct)
        {
            Interlocked.Increment(ref DownloadCalls);
            if (DownloadDelay > TimeSpan.Zero)
                await Task.Delay(DownloadDelay, ct);
            await File.WriteAllTextAsync(filePath, $"stream:{descriptor}", ct);
        }

        public async Task<bool> TryDownloadCaptionsAssAsync(
            string videoId, string languageCode, string filePath, CancellationToken ct)
        {
            if (languageCode != "en")
                return false;
            await File.WriteAllTextAsync(
                filePath, "[Events]\nDialogue: 0,0:00:00.00,0:00:01.00,Default,,0,0,0,,hi\n", ct);
            return true;
        }
    }

    /// <summary>Fake remux: concatenates the leg files so the test can verify which streams went in.</summary>
    private static void FakeRemux(string? video, string? audio, string output, CancellationToken ct)
    {
        var parts = new List<string>();
        if (video is not null) parts.Add(File.ReadAllText(video));
        if (audio is not null) parts.Add(File.ReadAllText(audio));
        File.WriteAllText(output, string.Join('+', parts));
    }

    private YouTubePreparer NewPreparer(FakeGateway gateway) => new(gateway, _dir, FakeRemux);

    [Fact]
    public async Task Prepare_BestSelection_ResolvesHighestQualityAndDefaultAudio_AndCommitsAtomically()
    {
        var gateway = new FakeGateway();
        var preparer = NewPreparer(gateway);

        var prepared = await preparer.PrepareAsync("dQw4w9WgXcQ", YouTubeStreamSelection.Best);

        Assert.True(File.Exists(prepared.AssetPath));
        Assert.Equal("stream:1080p|avc1|mp4+stream:opus|webm|en", File.ReadAllText(prepared.AssetPath));
        Assert.Empty(Directory.GetFiles(_dir, "*.partial")); // no stray temp legs after commit
        Assert.True(preparer.IsPrepared("dQw4w9WgXcQ", "1080p|avc1|mp4", "opus|webm|en"));
    }

    [Fact]
    public async Task Prepare_CacheHit_SkipsAllDownloads()
    {
        var gateway = new FakeGateway();
        var preparer = NewPreparer(gateway);
        var selection = new YouTubeStreamSelection("720p|avc1|mp4", "opus|webm|ja");

        await preparer.PrepareAsync("dQw4w9WgXcQ", selection);
        var downloadsAfterFirst = gateway.DownloadCalls;
        await preparer.PrepareAsync("dQw4w9WgXcQ", selection);

        Assert.Equal(downloadsAfterFirst, gateway.DownloadCalls); // second run served from cache
    }

    [Fact]
    public async Task Prepare_ConcurrentSameSelection_CoalescesToOneRun()
    {
        var gateway = new FakeGateway { DownloadDelay = TimeSpan.FromMilliseconds(150) };
        var preparer = NewPreparer(gateway);

        var tasks = Enumerable.Range(0, 8)
            .Select(_ => preparer.PrepareAsync("dQw4w9WgXcQ", YouTubeStreamSelection.Best))
            .ToArray();
        var results = await Task.WhenAll(tasks);

        Assert.All(results, r => Assert.Equal(results[0].AssetPath, r.AssetPath));
        Assert.Equal(2, gateway.DownloadCalls); // one video + one audio leg TOTAL, not per caller
    }

    [Fact]
    public async Task Prepare_SelectedStreamNoLongerOffered_ThrowsActionableError()
    {
        var preparer = NewPreparer(new FakeGateway());
        var ex = await Assert.ThrowsAsync<InvalidOperationException>(() =>
            preparer.PrepareAsync("dQw4w9WgXcQ", new YouTubeStreamSelection(Video: "4320p|av01|mp4")));
        Assert.Contains("no longer offered", ex.Message);
    }

    [Fact]
    public async Task Prepare_AudioOnly_ProducesAudioOnlyAsset_AndSubtitles()
    {
        var preparer = NewPreparer(new FakeGateway());
        var prepared = await preparer.PrepareAsync(
            "dQw4w9WgXcQ",
            new YouTubeStreamSelection(Audio: "opus|webm|en", SubtitleLanguage: "en") { IncludeVideo = false });

        Assert.Equal("stream:opus|webm|en", File.ReadAllText(prepared.AssetPath));
        Assert.NotNull(prepared.SubtitlePath);
        Assert.EndsWith(".ass", prepared.SubtitlePath);
        Assert.Contains("Dialogue:", File.ReadAllText(prepared.SubtitlePath!));
    }

    [Fact]
    public async Task Prepare_MissingSubtitleLanguage_StillPreparesAsset()
    {
        var preparer = NewPreparer(new FakeGateway());
        var prepared = await preparer.PrepareAsync(
            "dQw4w9WgXcQ", new YouTubeStreamSelection(SubtitleLanguage: "xx"));

        Assert.True(File.Exists(prepared.AssetPath));
        Assert.Null(prepared.SubtitlePath);
    }

    // ---- provider --------------------------------------------------------------------------------

    [Fact]
    public void Probe_ScoresCanonicalAndWatchUrls_AndIgnoresOthers()
    {
        var provider = new YouTubeDecoderProvider(NewPreparer(new FakeGateway()));

        Assert.Equal(1.0, provider.Probe("youtube://dQw4w9WgXcQ", MediaKind.Video));
        Assert.Equal(0.9, provider.Probe("https://youtu.be/dQw4w9WgXcQ", MediaKind.Audio));
        Assert.Equal(0.0, provider.Probe("/tmp/file.mp4", MediaKind.Video));
        // An audio-only selection offers no video track.
        var audioOnly = YouTubeSourceUri.Build("dQw4w9WgXcQ", new YouTubeStreamSelection { IncludeVideo = false });
        Assert.Equal(0.0, provider.Probe(audioOnly, MediaKind.Video));
        Assert.Equal(1.0, provider.Probe(audioOnly, MediaKind.Audio));
    }

    [Fact]
    public void Open_Unprepared_ThrowsReliableModeError()
    {
        var provider = new YouTubeDecoderProvider(NewPreparer(new FakeGateway()));
        var uri = YouTubeSourceUri.Build(
            "dQw4w9WgXcQ", new YouTubeStreamSelection("1080p|avc1|mp4", "opus|webm|en"));

        var ex = Assert.Throws<InvalidOperationException>(() => provider.OpenAudio(uri, options: null));
        Assert.Contains("not prepared", ex.Message);
    }
}
