using System.Collections.Concurrent;
using Xunit;

namespace S.Media.Source.YouTube.Tests;

/// <summary>All offline: the network seam (<see cref="IYouTubeGateway"/>) is faked and the remux step is
/// injected, so URI/cache/coalescing/provider behavior is covered without YouTube or FFmpeg natives.</summary>
public sealed class YouTubeModuleTests : IDisposable
{
    private readonly string _dir = Directory.CreateTempSubdirectory("yt-cache-").FullName;

    public void Dispose()
    {
        try { Directory.Delete(_dir, recursive: true); }
        catch { /* best effort */ }
    }

    // ---- URI codec -------------------------------------------------------------------------------

    [Theory]
    [InlineData("https://www.youtube.com/watch?v=dQw4w9WgXcQ")]
    [InlineData("https://youtu.be/dQw4w9WgXcQ")]
    [InlineData("https://www.youtube.com/shorts/dQw4w9WgXcQ")]
    [InlineData("youtube://dQw4w9WgXcQ")]
    public void TryParse_NormalizesEveryUrlForm_ToTheSameVideoId(string uri)
    {
        Assert.True(YouTubeSourceUri.TryParse(uri, out var id, out _));
        Assert.Equal("dQw4w9WgXcQ", id);
    }

    [Fact]
    public void BuildAndParse_RoundTripsSelections()
    {
        var selection = new YouTubeStreamSelection(
            Video: "1080p60|avc1.64002a|mp4",
            Audio: "opus|webm|en",
            SubtitleLanguage: "de");
        var uri = YouTubeSourceUri.Build("dQw4w9WgXcQ", selection);

        Assert.True(YouTubeSourceUri.TryParse(uri, out var id, out var parsed));
        Assert.Equal("dQw4w9WgXcQ", id);
        Assert.Equal(selection, parsed);
    }

    [Fact]
    public void BuildAndParse_RoundTripsAudioOnly()
    {
        var uri = YouTubeSourceUri.Build("dQw4w9WgXcQ", new YouTubeStreamSelection { IncludeVideo = false });
        Assert.True(YouTubeSourceUri.TryParse(uri, out _, out var parsed));
        Assert.False(parsed.IncludeVideo);
    }

    [Theory]
    [InlineData("/tmp/some/file.mp4")]
    [InlineData("ndi://camera-1")]
    [InlineData("not a uri at all")]
    public void TryParse_RejectsNonYouTubeSources(string uri) =>
        Assert.False(YouTubeSourceUri.TryParse(uri, out _, out _));

    // ---- prepare / cache -------------------------------------------------------------------------

    private sealed class FakeGateway : IYouTubeGateway
    {
        public int ManifestCalls;
        public int DownloadCalls;
        public TimeSpan DownloadDelay = TimeSpan.Zero;
        /// <summary>When set, the caption download writes a partial file then throws (simulating a mid-write
        /// caller cancellation) so the preparer's partial-cleanup path can be exercised (YT-01).</summary>
        public bool CaptionWritesPartialThenCancels;

        public YouTubeMediaManifest Manifest { get; set; } = new(
            "dQw4w9WgXcQ", "Test Video", "Test Author", TimeSpan.FromMinutes(3),
            [
                new YouTubeVideoStreamInfo("1080p|avc1|mp4", "1080p", 1080, 30, "avc1", "mp4", 100, 1000),
                new YouTubeVideoStreamInfo("720p|avc1|mp4", "720p", 720, 30, "avc1", "mp4", 50, 500),
            ],
            [
                new YouTubeAudioStreamInfo("opus|webm|en", "opus", "webm", 10, 128, "en", IsDefaultLanguage: true),
                new YouTubeAudioStreamInfo("opus|webm|ja", "opus", "webm", 10, 128, "ja", IsDefaultLanguage: false),
            ],
            [new YouTubeCaptionTrackInfo("en", "English", IsAutoGenerated: false)]);

        public Task<YouTubeMediaManifest> GetManifestAsync(string videoId, CancellationToken ct)
        {
            Interlocked.Increment(ref ManifestCalls);
            return Task.FromResult(Manifest);
        }

        public async Task DownloadStreamAsync(
            string videoId, string descriptor, string filePath, IProgress<double>? progress, CancellationToken ct)
        {
            Interlocked.Increment(ref DownloadCalls);
            if (DownloadDelay > TimeSpan.Zero)
                await Task.Delay(DownloadDelay, ct);
            await File.WriteAllTextAsync(filePath, $"stream:{descriptor}", ct);
        }

        public int ThumbnailCalls;
        public bool ThumbnailAvailable = true;

        public async Task<bool> TryDownloadThumbnailJpegAsync(string videoId, string filePath, CancellationToken ct)
        {
            Interlocked.Increment(ref ThumbnailCalls);
            if (!ThumbnailAvailable)
                return false;
            await File.WriteAllTextAsync(filePath, "thumb-bytes", ct);
            return true;
        }

        public async Task<bool> TryDownloadCaptionsAssAsync(
            string videoId, string languageCode, string filePath, CancellationToken ct)
        {
            if (languageCode != "en")
                return false;
            if (CaptionWritesPartialThenCancels)
            {
                await File.WriteAllTextAsync(filePath, "partial-caption-bytes", CancellationToken.None);
                throw new OperationCanceledException();
            }

            await File.WriteAllTextAsync(
                filePath, "[Events]\nDialogue: 0,0:00:00.00,0:00:01.00,Default,,0,0,0,,hi\n", ct);
            return true;
        }
    }

    /// <summary>Fake remux: concatenates the leg files so the test can verify which streams went in.</summary>
    private static void FakeRemux(string? video, string? audio, string? thumbnail, string output, CancellationToken ct)
    {
        var parts = new List<string>();
        if (video is not null) parts.Add(File.ReadAllText(video));
        if (audio is not null) parts.Add(File.ReadAllText(audio));
        if (thumbnail is not null) parts.Add(File.ReadAllText(thumbnail));
        File.WriteAllText(output, string.Join('+', parts));
    }

    private YouTubePreparer NewPreparer(FakeGateway gateway) => new(gateway, _dir, FakeRemux);

    [Fact]
    public async Task Prepare_BestSelection_ResolvesHighestQualityAndDefaultAudio_AndCommitsAtomically()
    {
        var gateway = new FakeGateway();
        var preparer = NewPreparer(gateway);

        var prepared = await preparer.PrepareAsync("dQw4w9WgXcQ", YouTubeStreamSelection.Best);

        Assert.True(File.Exists(prepared.AssetPath));
        Assert.Equal("stream:1080p|avc1|mp4+stream:opus|webm|en", File.ReadAllText(prepared.AssetPath));
        Assert.Empty(Directory.GetFiles(_dir, "*.partial")); // no stray temp legs after commit
        Assert.True(preparer.IsPrepared("dQw4w9WgXcQ", "1080p|avc1|mp4", "opus|webm|en"));
    }

    [Fact]
    public async Task Prepare_CacheHit_SkipsAllDownloads()
    {
        var gateway = new FakeGateway();
        var preparer = NewPreparer(gateway);
        var selection = new YouTubeStreamSelection("720p|avc1|mp4", "opus|webm|ja");

        await preparer.PrepareAsync("dQw4w9WgXcQ", selection);
        var downloadsAfterFirst = gateway.DownloadCalls;
        await preparer.PrepareAsync("dQw4w9WgXcQ", selection);

        Assert.Equal(downloadsAfterFirst, gateway.DownloadCalls); // second run served from cache
    }

    [Fact]
    public async Task Prepare_ConcurrentSameSelection_CoalescesToOneRun()
    {
        var gateway = new FakeGateway { DownloadDelay = TimeSpan.FromMilliseconds(150) };
        var preparer = NewPreparer(gateway);

        var tasks = Enumerable.Range(0, 8)
            .Select(_ => preparer.PrepareAsync("dQw4w9WgXcQ", YouTubeStreamSelection.Best))
            .ToArray();
        var results = await Task.WhenAll(tasks);

        Assert.All(results, r => Assert.Equal(results[0].AssetPath, r.AssetPath));
        Assert.Equal(2, gateway.DownloadCalls); // one video + one audio leg TOTAL, not per caller
    }

    [Fact]
    public async Task Prepare_DifferentRequestsResolvingToSameAsset_SerializeOneAtomicRemux()
    {
        // "best" and this explicit pair resolve to the same final cache key but have different pre-resolution
        // coalescing keys. They must share the asset-path lease rather than write the same .partial concurrently.
        var gateway = new FakeGateway { DownloadDelay = TimeSpan.FromMilliseconds(100) };
        var remuxCalls = 0;
        var preparer = new YouTubePreparer(gateway, _dir, (v, a, t, output, ct) =>
        {
            Interlocked.Increment(ref remuxCalls);
            Thread.Sleep(100);
            FakeRemux(v, a, t, output, ct);
        });

        var best = preparer.PrepareAsync("dQw4w9WgXcQ", YouTubeStreamSelection.Best);
        var explicitPair = preparer.PrepareAsync(
            "dQw4w9WgXcQ", new YouTubeStreamSelection("1080p|avc1|mp4", "opus|webm|en"));
        var results = await Task.WhenAll(best, explicitPair);

        Assert.Equal(results[0].AssetPath, results[1].AssetPath);
        Assert.Equal(1, remuxCalls);
        Assert.Empty(Directory.GetFiles(_dir, "*.partial"));
    }

    [Fact]
    public async Task Prepare_OneCallerCancels_OthersStillComplete_SharedRunSurvives()
    {
        // YT-02: cancelling one caller's wait must not abort the shared prepare other callers joined.
        var gateway = new FakeGateway { DownloadDelay = TimeSpan.FromMilliseconds(300) };
        var preparer = NewPreparer(gateway);

        using var cancelFirst = new CancellationTokenSource();
        var a = preparer.PrepareAsync("dQw4w9WgXcQ", YouTubeStreamSelection.Best, cancellationToken: cancelFirst.Token);
        var b = preparer.PrepareAsync("dQw4w9WgXcQ", YouTubeStreamSelection.Best);
        var c = preparer.PrepareAsync("dQw4w9WgXcQ", YouTubeStreamSelection.Best);

        cancelFirst.Cancel();
        await Assert.ThrowsAnyAsync<OperationCanceledException>(() => a);

        var rb = await b;
        var rc = await c;
        Assert.Equal(rb.AssetPath, rc.AssetPath);
        Assert.True(File.Exists(rb.AssetPath));
        Assert.Equal(2, gateway.DownloadCalls); // one shared run (video+audio), not aborted by the cancel
    }

    [Fact]
    public async Task Prepare_CaptionDownloadCancels_PropagatesAndLeavesNoPartial()
    {
        // YT-01: a caller cancellation during caption work propagates and the partial caption is cleaned up.
        var gateway = new FakeGateway { CaptionWritesPartialThenCancels = true };
        var preparer = NewPreparer(gateway);

        await Assert.ThrowsAnyAsync<OperationCanceledException>(() => preparer.PrepareAsync(
            "dQw4w9WgXcQ",
            new YouTubeStreamSelection(Audio: "opus|webm|en", SubtitleLanguage: "en") { IncludeVideo = false }));

        Assert.Empty(Directory.GetFiles(_dir, "*.partial")); // partial caption removed by the finally
        Assert.Empty(Directory.GetFiles(_dir, "*.ass"));      // nothing committed
    }

    [Fact]
    public async Task Prepare_WithMaxCacheBytes_EvictsOldestAsset_KeepsJustPrepared()
    {
        // YT-03: after a successful prepare, LRU eviction trims the cache but never the asset just made.
        var gateway = new FakeGateway();
        var preparer = new YouTubePreparer(gateway, _dir, FakeRemux, maxCacheBytes: 60);

        var first = await preparer.PrepareAsync(
            "dQw4w9WgXcQ", new YouTubeStreamSelection("1080p|avc1|mp4", "opus|webm|en"));
        var second = await preparer.PrepareAsync(
            "dQw4w9WgXcQ", new YouTubeStreamSelection("720p|avc1|mp4", "opus|webm|ja"));

        Assert.True(File.Exists(second.AssetPath));  // just-prepared asset protected
        Assert.False(File.Exists(first.AssetPath));  // older asset evicted to stay under the cap
    }

    [Fact]
    public async Task Prepare_SelectedStreamNoLongerOffered_ThrowsActionableError()
    {
        var preparer = NewPreparer(new FakeGateway());
        var ex = await Assert.ThrowsAsync<InvalidOperationException>(() =>
            preparer.PrepareAsync("dQw4w9WgXcQ", new YouTubeStreamSelection(Video: "4320p|av01|mp4")));
        Assert.Contains("no longer offered", ex.Message);
    }

    [Fact]
    public async Task Prepare_AudioOnly_ProducesAudioOnlyAsset_AndSubtitles()
    {
        var preparer = NewPreparer(new FakeGateway());
        var prepared = await preparer.PrepareAsync(
            "dQw4w9WgXcQ",
            new YouTubeStreamSelection(Audio: "opus|webm|en", SubtitleLanguage: "en") { IncludeVideo = false });

        Assert.Equal("stream:opus|webm|en", File.ReadAllText(prepared.AssetPath));
        Assert.NotNull(prepared.SubtitlePath);
        Assert.EndsWith(".ass", prepared.SubtitlePath);
        Assert.Contains("Dialogue:", File.ReadAllText(prepared.SubtitlePath!));
    }

    [Fact]
    public async Task Prepare_MissingSubtitleLanguage_StillPreparesAsset()
    {
        var preparer = NewPreparer(new FakeGateway());
        var prepared = await preparer.PrepareAsync(
            "dQw4w9WgXcQ", new YouTubeStreamSelection(SubtitleLanguage: "xx"));

        Assert.True(File.Exists(prepared.AssetPath));
        Assert.Null(prepared.SubtitlePath);
    }

    // ---- provider --------------------------------------------------------------------------------

    [Fact]
    public void Probe_ScoresCanonicalAndWatchUrls_AndIgnoresOthers()
    {
        var provider = new YouTubeDecoderProvider(NewPreparer(new FakeGateway()));

        Assert.Equal(1.0, provider.Probe("youtube://dQw4w9WgXcQ", MediaKind.Video));
        Assert.Equal(0.9, provider.Probe("https://youtu.be/dQw4w9WgXcQ", MediaKind.Audio));
        Assert.Equal(0.0, provider.Probe("/tmp/file.mp4", MediaKind.Video));
        // An audio-only selection offers no video track.
        var audioOnly = YouTubeSourceUri.Build("dQw4w9WgXcQ", new YouTubeStreamSelection { IncludeVideo = false });
        Assert.Equal(0.0, provider.Probe(audioOnly, MediaKind.Video));
        Assert.Equal(1.0, provider.Probe(audioOnly, MediaKind.Audio));
    }

    // ---- embedded thumbnail (Ideas.txt) ----------------------------------------------------------

    [Fact]
    public void Uri_RoundTripsThumbnailFlag()
    {
        var uri = YouTubeSourceUri.Build(
            "dQw4w9WgXcQ",
            new YouTubeStreamSelection("1080p|avc1|mp4", "opus|webm|en") { IncludeThumbnail = true });
        Assert.Contains("thumb=1", uri);

        Assert.True(YouTubeSourceUri.TryParse(uri, out _, out var selection));
        Assert.True(selection!.IncludeThumbnail);

        var without = YouTubeSourceUri.Build(
            "dQw4w9WgXcQ", new YouTubeStreamSelection("1080p|avc1|mp4", "opus|webm|en"));
        Assert.DoesNotContain("thumb", without);
        Assert.True(YouTubeSourceUri.TryParse(without, out _, out var plain));
        Assert.False(plain!.IncludeThumbnail);
    }

    [Fact]
    public async Task Prepare_WithThumbnail_EmbedsIt_AndIsADistinctCacheIdentity()
    {
        var gateway = new FakeGateway();
        var preparer = NewPreparer(gateway);
        var selection = new YouTubeStreamSelection("720p|avc1|mp4", "opus|webm|en");

        var plain = await preparer.PrepareAsync("dQw4w9WgXcQ", selection);
        var withThumb = await preparer.PrepareAsync(
            "dQw4w9WgXcQ", selection with { IncludeThumbnail = true });

        // Same A/V pair with and without the thumbnail must be DIFFERENT assets: the no-network open
        // path maps a thumb=1 URI to the thumb-inclusive identity and must never get a lying asset.
        Assert.NotEqual(plain.AssetPath, withThumb.AssetPath);
        Assert.Equal("stream:720p|avc1|mp4+stream:opus|webm|en", File.ReadAllText(plain.AssetPath));
        Assert.Equal(
            "stream:720p|avc1|mp4+stream:opus|webm|en+thumb-bytes", File.ReadAllText(withThumb.AssetPath));
        Assert.True(withThumb.ResolvedSelection.IncludeThumbnail);
        Assert.True(preparer.IsPrepared("dQw4w9WgXcQ", "720p|avc1|mp4", "opus|webm|en", includeThumbnail: true));
    }

    [Fact]
    public async Task Prepare_ThumbnailJpeg_IsDownloadedOncePerVideo_AcrossSelections()
    {
        var gateway = new FakeGateway();
        var preparer = NewPreparer(gateway);

        await preparer.PrepareAsync(
            "dQw4w9WgXcQ", new YouTubeStreamSelection("1080p|avc1|mp4", "opus|webm|en") { IncludeThumbnail = true });
        await preparer.PrepareAsync(
            "dQw4w9WgXcQ", new YouTubeStreamSelection("720p|avc1|mp4", "opus|webm|en") { IncludeThumbnail = true });

        Assert.Equal(1, gateway.ThumbnailCalls); // per-video .jpg cache reused by the second selection
    }

    [Fact]
    public async Task Prepare_ThumbnailUnavailable_FailsInsteadOfCommittingALyingAsset()
    {
        var gateway = new FakeGateway { ThumbnailAvailable = false };
        var preparer = NewPreparer(gateway);
        var selection = new YouTubeStreamSelection("720p|avc1|mp4", "opus|webm|en") { IncludeThumbnail = true };

        var ex = await Assert.ThrowsAsync<InvalidOperationException>(
            () => preparer.PrepareAsync("dQw4w9WgXcQ", selection));
        Assert.Contains("thumbnail", ex.Message, StringComparison.OrdinalIgnoreCase);
        Assert.False(preparer.IsPrepared("dQw4w9WgXcQ", "720p|avc1|mp4", "opus|webm|en", includeThumbnail: true));
    }

    [Fact]
    public void Open_ThumbUri_MapsToTheThumbInclusiveAsset()
    {
        var preparer = NewPreparer(new FakeGateway());
        var provider = new YouTubeDecoderProvider(preparer);
        var uri = YouTubeSourceUri.Build(
            "dQw4w9WgXcQ",
            new YouTubeStreamSelection("1080p|avc1|mp4", "opus|webm|en") { IncludeThumbnail = true });

        // Unprepared: proves the OPEN path resolves the thumb-inclusive identity (reliable-mode error,
        // not a silent fallback onto the thumbnail-less asset).
        var ex = Assert.Throws<InvalidOperationException>(() => provider.OpenAudio(uri, options: null));
        Assert.Contains("not prepared", ex.Message);
    }

    [Fact]
    public void Open_Unprepared_ThrowsReliableModeError()
    {
        var provider = new YouTubeDecoderProvider(NewPreparer(new FakeGateway()));
        var uri = YouTubeSourceUri.Build(
            "dQw4w9WgXcQ", new YouTubeStreamSelection("1080p|avc1|mp4", "opus|webm|en"));

        var ex = Assert.Throws<InvalidOperationException>(() => provider.OpenAudio(uri, options: null));
        Assert.Contains("not prepared", ex.Message);
    }
}
