using YoutubeExplode;
using YoutubeExplode.Videos;
using YoutubeExplode.Videos.ClosedCaptions;
using YoutubeExplode.Videos.Streams;

namespace S.Media.Source.YouTube;

/// <summary>One selectable video stream, described in operator terms (for the stream-picker dialogs).</summary>
public sealed record YouTubeVideoStreamInfo(
    string Descriptor, string QualityLabel, int Height, int Framerate,
    string Codec, string Container, long SizeBytes, long BitrateBps);

/// <summary>One selectable audio stream (YouTube ships audio separately from video at high quality).</summary>
public sealed record YouTubeAudioStreamInfo(
    string Descriptor, string Codec, string Container, long SizeBytes, long BitrateBps,
    string? Language, bool IsDefaultLanguage);

/// <summary>One selectable caption track.</summary>
public sealed record YouTubeCaptionTrackInfo(string LanguageCode, string LanguageName, bool IsAutoGenerated);

/// <summary>Resolved metadata + stream manifest for one video - everything the selection UI needs.</summary>
public sealed record YouTubeMediaManifest(
    string VideoId,
    string Title,
    string Author,
    TimeSpan? Duration,
    IReadOnlyList<YouTubeVideoStreamInfo> VideoStreams,
    IReadOnlyList<YouTubeAudioStreamInfo> AudioStreams,
    IReadOnlyList<YouTubeCaptionTrackInfo> CaptionTracks);

/// <summary>
/// The network seam of the module: everything that talks to YouTube goes through this interface so the
/// cache/preparer/provider logic tests offline with a fake. The real implementation wraps YoutubeExplode.
/// </summary>
public interface IYouTubeGateway
{
    Task<YouTubeMediaManifest> GetManifestAsync(string videoId, CancellationToken cancellationToken);

    /// <summary>Downloads the stream matching <paramref name="descriptor"/> (video or audio) to a file.</summary>
    Task DownloadStreamAsync(
        string videoId, string descriptor, string filePath,
        IProgress<double>? progress, CancellationToken cancellationToken);

    /// <summary>Downloads the caption track for <paramref name="languageCode"/> as an ASS subtitle document -
    /// YouTube's rich <c>json3</c> converted to ASS so colour, alpha, bold/italic/underline and per-cue window
    /// positioning survive - or returns false when the language isn't offered.</summary>
    Task<bool> TryDownloadCaptionsAssAsync(
        string videoId, string languageCode, string filePath, CancellationToken cancellationToken);
}

/// <summary>YoutubeExplode-backed gateway. Descriptors are produced and re-matched here so the format
/// stays private to the module: video <c>label|codec|container</c>, audio <c>codec|container|language</c>.</summary>
public sealed class YoutubeExplodeGateway : IYouTubeGateway
{
    private readonly YoutubeClient _client = new();

    internal static string DescribeVideo(IVideoStreamInfo s) =>
        $"{s.VideoQuality.Label}|{s.VideoCodec}|{s.Container.Name}";

    internal static string DescribeAudio(IAudioStreamInfo s) =>
        $"{s.AudioCodec}|{s.Container.Name}|{s.AudioLanguage?.Code ?? ""}";

    public async Task<YouTubeMediaManifest> GetManifestAsync(string videoId, CancellationToken cancellationToken)
    {
        var id = VideoId.Parse(videoId);
        var video = await _client.Videos.GetAsync(id, cancellationToken).ConfigureAwait(false);
        var manifest = await _client.Videos.Streams.GetManifestAsync(id, cancellationToken).ConfigureAwait(false);

        var videoStreams = manifest.GetVideoOnlyStreams()
            .OrderByDescending(s => s.VideoQuality)
            .Select(s => new YouTubeVideoStreamInfo(
                DescribeVideo(s), s.VideoQuality.Label, s.VideoResolution.Height, s.VideoQuality.Framerate,
                s.VideoCodec, s.Container.Name, s.Size.Bytes, (long)s.Bitrate.BitsPerSecond))
            .ToList();

        var audioStreams = manifest.GetAudioOnlyStreams()
            .OrderByDescending(s => s.Bitrate)
            .Select(s => new YouTubeAudioStreamInfo(
                DescribeAudio(s), s.AudioCodec, s.Container.Name, s.Size.Bytes, (long)s.Bitrate.BitsPerSecond,
                s.AudioLanguage?.Code, s.IsAudioLanguageDefault ?? false))
            .ToList();

        var captions = new List<YouTubeCaptionTrackInfo>();
        try
        {
            var captionManifest = await _client.Videos.ClosedCaptions
                .GetManifestAsync(id, cancellationToken).ConfigureAwait(false);
            captions.AddRange(captionManifest.Tracks.Select(t =>
                new YouTubeCaptionTrackInfo(t.Language.Code, t.Language.Name, t.IsAutoGenerated)));
        }
        catch (Exception ex) when (!cancellationToken.IsCancellationRequested)
        {
            // Captions are best-effort metadata - their absence must not block stream selection. But a
            // caller cancellation is NOT best-effort: let it propagate (YT-01).
            _ = ex;
        }

        return new YouTubeMediaManifest(
            id.Value, video.Title, video.Author.ChannelTitle, video.Duration,
            videoStreams, audioStreams, captions);
    }

    public async Task DownloadStreamAsync(
        string videoId, string descriptor, string filePath,
        IProgress<double>? progress, CancellationToken cancellationToken)
    {
        var id = VideoId.Parse(videoId);
        var manifest = await _client.Videos.Streams.GetManifestAsync(id, cancellationToken).ConfigureAwait(false);
        IStreamInfo? stream =
            manifest.GetVideoOnlyStreams().FirstOrDefault(s => DescribeVideo(s) == descriptor)
            ?? (IStreamInfo?)manifest.GetAudioOnlyStreams().FirstOrDefault(s => DescribeAudio(s) == descriptor);
        if (stream is null)
            throw new InvalidOperationException(
                $"YouTube stream '{descriptor}' is no longer offered for video '{videoId}' - reselect streams.");

        await _client.Videos.Streams
            .DownloadAsync(stream, filePath, progress, cancellationToken).ConfigureAwait(false);
    }

    public async Task<bool> TryDownloadCaptionsAssAsync(
        string videoId, string languageCode, string filePath, CancellationToken cancellationToken)
    {
        var id = VideoId.Parse(videoId);
        ClosedCaptionManifest captionManifest;
        try
        {
            captionManifest = await _client.Videos.ClosedCaptions
                .GetManifestAsync(id, cancellationToken).ConfigureAwait(false);
        }
        catch (Exception ex) when (!cancellationToken.IsCancellationRequested)
        {
            _ = ex;
            return false;
        }

        var trackInfo = captionManifest.Tracks
            .FirstOrDefault(t => string.Equals(t.Language.Code, languageCode, StringComparison.OrdinalIgnoreCase));
        if (trackInfo is null)
            return false;

        // Preferred path (MANUAL tracks only): fetch YouTube's rich json3 timedtext straight from the track's
        // authorized base URL and convert it to ASS, so colour, alpha, bold/italic/underline and the per-cue
        // window positioning all survive into libass. YoutubeExplode itself only ever exposes flat SRT, which
        // drops all of that. Auto-generated (ASR) tracks carry NO styling or positioning - json3 buys nothing
        // there, and its word-level "rolling"/append events can render as duplicated overlapping lines - so
        // those take the flat-caption path below (YoutubeExplode merges rolling ASR into clean lines).
        if (!trackInfo.IsAutoGenerated)
        {
            try
            {
                var json3 = await Http.GetStringAsync(
                    WithCaptionFormat(trackInfo.Url, "json3"), cancellationToken).ConfigureAwait(false);
                if (!string.IsNullOrWhiteSpace(json3))
                {
                    var ass = YouTubeCaptionConverter.Json3ToAss(json3);
                    await File.WriteAllTextAsync(filePath, ass, cancellationToken).ConfigureAwait(false);
                    return true;
                }
            }
            catch (Exception ex) when (!cancellationToken.IsCancellationRequested)
            {
                // Fall through to the flat-caption fallback below (but never swallow a caller cancellation).
                _ = ex;
            }
        }

        // Flat path: the primary route for auto-generated tracks, and the fallback when json3 is unavailable/
        // unparseable for a manual track. Flat captions via YoutubeExplode, wrapped in the same ASS scaffold
        // (plain white, bottom-centre). Still a valid ASS sidecar, so the direct-libass path applies.
        try
        {
            var track = await _client.Videos.ClosedCaptions
                .GetAsync(trackInfo, cancellationToken).ConfigureAwait(false);
            var plain = track.Captions
                .Where(c => !string.IsNullOrWhiteSpace(c.Text))
                .Select(c => (c.Text.Trim(),
                    (long)c.Offset.TotalMilliseconds, (long)c.Duration.TotalMilliseconds));
            await File.WriteAllTextAsync(
                filePath, YouTubeCaptionConverter.PlainCaptionsToAss(plain), cancellationToken).ConfigureAwait(false);
            return true;
        }
        catch (Exception ex) when (!cancellationToken.IsCancellationRequested)
        {
            _ = ex;
            return false;
        }
    }

    /// <summary>Sets the timedtext response format (e.g. <c>json3</c>) on a caption base URL, replacing any
    /// existing <c>fmt</c>/<c>format</c> parameter. Also drops <c>xosf</c>, which yt-dlp strips because
    /// <c>xosf=1</c> yields "undesirable text position data" for json3/srv* subtitles
    /// (https://github.com/yt-dlp/yt-dlp/issues/13654). The base URL is already authorized; <c>fmt</c> is a
    /// free query parameter (yt-dlp appends it the same way).</summary>
    public static string WithCaptionFormat(string url, string fmt)
    {
        var split = url.Split('?', 2);
        var query = split.Length > 1
            ? split[1].Split('&', StringSplitOptions.RemoveEmptyEntries)
                .Where(p => !p.StartsWith("fmt=", StringComparison.OrdinalIgnoreCase)
                         && !p.StartsWith("format=", StringComparison.OrdinalIgnoreCase)
                         && !p.StartsWith("xosf=", StringComparison.OrdinalIgnoreCase))
                .ToList()
            : [];
        query.Add("fmt=" + fmt);
        return split[0] + "?" + string.Join("&", query);
    }

    // Shared client for the raw timedtext GET. A browser-ish User-Agent keeps YouTube from short-changing the
    // response; the URL itself is pre-authorized via the player response, so no cookies/keys are needed.
    private static readonly HttpClient Http = CreateCaptionHttpClient();

    private static HttpClient CreateCaptionHttpClient()
    {
        var http = new HttpClient();
        http.DefaultRequestHeaders.TryAddWithoutValidation(
            "User-Agent",
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36");
        return http;
    }
}
