#!/usr/bin/env bash
# BUILD-02: emit a per-artifact SBOM / provenance manifest for the bundled native libraries. For every native
# library shipped next to the app it records the upstream project, the pinned version, the source URL, the
# license, and the SHA-256 of the *exact* file being shipped — so a release artifact carries an auditable record
# of what native code it contains and where it came from. Written into the publish dir so it travels with the
# artifact. This is advisory provenance: it never fails the build.
#
# Usage: generate-native-sbom.sh <rid> <publish-dir>
set -uo pipefail
rid="${1:?usage: generate-native-sbom.sh <rid> <publish-dir>}"
pub="${2:?usage: generate-native-sbom.sh <rid> <publish-dir>}"
out="$pub/native-provenance.txt"

# filename-prefix : upstream project : pinned version : source URL : license
# (prefix matches the start of the shipped filename; longest match wins, so libavcodec beats libav*)
provenance() {
  case "$1" in
    libavcodec*|libavformat*|libavutil*|libswresample*|libswscale*|avcodec*|avformat*|avutil*|swresample*|swscale*)
      echo "FFmpeg|n8.1 (BtbN GPL build)|https://github.com/BtbN/FFmpeg-Builds|GPL-3.0-or-later" ;;
    libportaudio*|portaudio*)
      echo "PortAudio|v19.7.0|https://github.com/PortAudio/portaudio|MIT" ;;
    libportmidi*|portmidi*)
      echo "PortMidi|v2.0.7|https://github.com/PortMidi/portmidi|MIT" ;;
    libminiaudio*|miniaudio*)
      echo "miniaudio|0.11.25|https://github.com/mackron/miniaudio|MIT-0/Unlicense" ;;
    libass*|ass.dll)
      echo "libass|distro/vcpkg|https://github.com/libass/libass|ISC" ;;
    libndi*|Processing.NDI*)
      echo "NDI SDK Runtime|v6|https://ndi.video|NDI-SDK-EULA (proprietary redist)" ;;
    libprojectM*|projectM-4*)
      echo "projectM|4.1.6|https://github.com/projectM-visualizer/projectm|LGPL-2.1 (dynamic link only)" ;;
    libmmd_bullet*|mmd_bullet*)
      echo "mmd_bullet (Bullet physics shim)|Bullet 3.25 (vendored)|MediaFramework/Native/mmd_bullet + External/bullet3|zlib" ;;
    *SDL3*|libSDL3*)
      echo "SDL3|NuGet SDL3-CS native|https://github.com/libsdl-org/SDL|zlib" ;;
    *)
      echo "" ;;
  esac
}

sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then sha256sum "$1" | awk '{print $1}';
  elif command -v shasum   >/dev/null 2>&1; then shasum -a 256 "$1" | awk '{print $1}';
  else echo "(sha256 tool unavailable)"; fi
}

{
  echo "# Native dependency provenance (SBOM) for HaPlay.Desktop"
  echo "# rid: $rid"
  echo "# generated by scripts/generate-native-sbom.sh (BUILD-02)"
  echo "#"
  echo "# file | sha256 | project | version | source | license"
} > "$out"

shopt -s nullglob
found=0
for f in "$pub"/*.so "$pub"/*.so.* "$pub"/*.dll "$pub"/*.dylib; do
  [ -e "$f" ] || continue
  name="$(basename "$f")"
  meta="$(provenance "$name")"
  if [ -z "$meta" ]; then
    meta="(first-party or unlisted)|-|-|-"
  fi
  IFS='|' read -r project version source license <<<"$meta"
  printf '%s | %s | %s | %s | %s | %s\n' \
    "$name" "$(sha256_of "$f")" "$project" "$version" "$source" "$license" >> "$out"
  found=$((found + 1))
done

echo "BUILD-02: wrote native SBOM for $found library(ies) -> $out"
cat "$out"
