using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using HaPlay.Models;
using HaPlay.Playback;
using HaPlay.ViewModels.Dialogs;
using S.Media.Session;
using S.Media.Source.YouTube;
using Xunit;

namespace HaPlay.Tests;

/// <summary>
/// Gate-5 UI slice, all offline (fake gateway + injected remux): the stream-selection dialog VM
/// (resolve → pick separate video/audio/subtitle streams → download &amp; cache), the playlist-item →
/// canonical-URI mapping, and the cue/deck subtitle sidecar flow.
/// </summary>
public sealed class YouTubeIntegrationTests : IDisposable
{
    private readonly string _dir = Directory.CreateTempSubdirectory("yt-ui-").FullName;

    public void Dispose()
    {
        try { Directory.Delete(_dir, recursive: true); }
        catch { /* best effort */ }
    }

    private sealed class FakeGateway : IYouTubeGateway
    {
        public YouTubeMediaManifest Manifest { get; set; } = new(
            "dQw4w9WgXcQ", "Never Gonna", "Rick", TimeSpan.FromMinutes(3),
            [
                new YouTubeVideoStreamInfo("1080p|avc1|mp4", "1080p", 1080, 30, "avc1", "mp4", 100, 1000),
                new YouTubeVideoStreamInfo("720p|avc1|mp4", "720p", 720, 30, "avc1", "mp4", 50, 500),
            ],
            [
                new YouTubeAudioStreamInfo("opus|webm|en", "opus", "webm", 10, 128, "en", IsDefaultLanguage: true),
                new YouTubeAudioStreamInfo("opus|webm|ja", "opus", "webm", 10, 128, "ja", IsDefaultLanguage: false),
            ],
            [new YouTubeCaptionTrackInfo("en", "English", IsAutoGenerated: false)]);

        public Task<YouTubeMediaManifest> GetManifestAsync(string videoId, CancellationToken ct) =>
            Task.FromResult(Manifest);

        public async Task DownloadStreamAsync(
            string videoId, string descriptor, string filePath, IProgress<double>? progress, CancellationToken ct) =>
            await File.WriteAllTextAsync(filePath, $"stream:{descriptor}", ct);

        public async Task<bool> TryDownloadCaptionsAssAsync(
            string videoId, string languageCode, string filePath, CancellationToken ct)
        {
            if (languageCode != "en")
                return false;
            await File.WriteAllTextAsync(
                filePath, "[Events]\nDialogue: 0,0:00:00.00,0:00:01.00,Default,,0,0,0,,hi\n", ct);
            return true;
        }
    }

    private static void FakeRemux(string? video, string? audio, string output, CancellationToken ct) =>
        File.WriteAllText(output, "muxed");

    private (AddYouTubeDialogViewModel Vm, YouTubePreparer Preparer) NewDialog()
    {
        var gateway = new FakeGateway();
        var preparer = new YouTubePreparer(gateway, _dir, FakeRemux);
        return (new AddYouTubeDialogViewModel(gateway, preparer), preparer);
    }

    [Fact]
    public async Task Dialog_ResolveThenPrepare_ProducesItemWithResolvedStreams_AndCaptionSidecar()
    {
        var (vm, _) = NewDialog();
        vm.Url = "https://youtu.be/dQw4w9WgXcQ";
        await vm.ResolveCommand.ExecuteAsync(null);

        Assert.True(vm.HasManifest);
        Assert.Equal("Never Gonna", vm.VideoTitle);
        Assert.Equal(2, vm.VideoStreams.Count);
        Assert.Equal(2, vm.AudioStreams.Count);
        Assert.Equal(2, vm.SubtitleTracks.Count); // "(none)" + en
        Assert.Equal("1080p|avc1|mp4", vm.SelectedVideoStream!.Info.Descriptor); // best by default
        Assert.Equal("opus|webm|en", vm.SelectedAudioStream!.Info.Descriptor);   // default language

        vm.SelectedVideoStream = vm.VideoStreams.First(o => o.Info.Descriptor == "720p|avc1|mp4");
        vm.SelectedSubtitleTrack = vm.SubtitleTracks.First(o => o.Info is not null);

        YouTubePlaylistItem? item = null;
        vm.Completed += produced => item = produced;
        await vm.PrepareAndAcceptCommand.ExecuteAsync(null);

        Assert.NotNull(item);
        Assert.Equal("dQw4w9WgXcQ", item!.VideoId);
        Assert.Equal("720p|avc1|mp4", item.VideoStreamDescriptor);
        Assert.Equal("opus|webm|en", item.AudioStreamDescriptor);
        Assert.Equal("en", item.SubtitleLanguage);
        var subtitle = Assert.Single(item.Subtitles);
        Assert.True(File.Exists(subtitle.Path), "caption sidecar must exist in the cache");
    }

    [Fact]
    public async Task Dialog_AudioOnly_SkipsVideoStream()
    {
        var (vm, preparer) = NewDialog();
        vm.Url = "youtube://dQw4w9WgXcQ";
        await vm.ResolveCommand.ExecuteAsync(null);
        vm.AudioOnly = true;

        YouTubePlaylistItem? item = null;
        vm.Completed += produced => item = produced;
        await vm.PrepareAndAcceptCommand.ExecuteAsync(null);

        Assert.NotNull(item);
        Assert.True(item!.AudioOnly);
        Assert.Null(item.VideoStreamDescriptor);
        Assert.True(preparer.IsPrepared("dQw4w9WgXcQ", null, "opus|webm|en"));
    }

    [Fact]
    public async Task Dialog_BadUrl_SetsValidation_WithoutThrowing()
    {
        var (vm, _) = NewDialog();
        vm.Url = "not a link";
        await vm.ResolveCommand.ExecuteAsync(null);
        Assert.False(vm.HasManifest);
        Assert.NotNull(vm.ValidationMessage);
    }

    [Fact]
    public void PlaylistItem_MapsToCanonicalUri_AndRoundTripsProjectJson()
    {
        var item = new YouTubePlaylistItem("dQw4w9WgXcQ")
        {
            Title = "T",
            VideoStreamDescriptor = "1080p|avc1|mp4",
            AudioStreamDescriptor = "opus|webm|en",
            SubtitleLanguage = "en",
        };

        var uri = HaPlayPlaybackHelpers.BuildYouTubeUri(item);
        Assert.True(YouTubeSourceUri.TryParse(uri, out var id, out var selection));
        Assert.Equal("dQw4w9WgXcQ", id);
        Assert.Equal("1080p|avc1|mp4", selection!.Video);
        Assert.Equal("opus|webm|en", selection.Audio);

        // Persist round-trip through the project's polymorphic playlist union.
        var project = new HaPlayProject { CueLists = { new CueList { Name = "L" } } };
        project.CueLists[0].Nodes.Add(new MediaCueNode { Number = "1", Label = "yt", Source = item });
        var json = System.Text.Json.JsonSerializer.Serialize(
            project, HaPlayProjectJsonContext.Default.HaPlayProject);
        var back = System.Text.Json.JsonSerializer.Deserialize(
            json, HaPlayProjectJsonContext.Default.HaPlayProject)!;
        var restored = Assert.IsType<YouTubePlaylistItem>(
            Assert.IsType<MediaCueNode>(back.CueLists[0].Nodes[0]).Source);
        Assert.Equal(item.VideoStreamDescriptor, restored.VideoStreamDescriptor);
        Assert.Equal(item.AudioStreamDescriptor, restored.AudioStreamDescriptor);
    }

    [Fact]
    public void CueMapper_MapsMmdCue_ToMmdUri_WithManualCameraParams()
    {
        var compositionId = Guid.NewGuid();
        var cueList = new CueList
        {
            Name = "Act",
            Compositions = { new CueComposition { Id = compositionId, Width = 1920, Height = 1080 } },
            Nodes =
            {
                new MediaCueNode
                {
                    Number = "1",
                    Label = "mmd",
                    Source = new MmdPlaylistItem("/tmp/model.pmx")
                    {
                        MotionPath = "/tmp/dance.vmd",
                        CameraDistance = -22,
                        CameraTargetY = 11.5,
                        CameraFovDeg = 42,
                    },
                    VideoPlacements = { new CueVideoPlacement { CompositionId = compositionId } },
                },
            },
        };

        var document = HaPlayShowMapper.ToShowDocument(cueList);
        var clip = Assert.Single(document.Clips);
        Assert.True(S.Media.Source.MMD.MmdSourceUri.TryParse(clip.MediaPath, out var request));
        Assert.Equal("/tmp/model.pmx", request!.ModelPath);
        Assert.Equal("/tmp/dance.vmd", request.MotionPath);
        Assert.Equal(-22f, request.CameraDistance);
        Assert.Equal(42f, request.CameraFovDegrees);
        Assert.Equal(11.5f, request.CameraTarget!.Value.Y);

        // Persist round-trip through the polymorphic playlist union.
        var project = new HaPlayProject { CueLists = { cueList } };
        var json = System.Text.Json.JsonSerializer.Serialize(
            project, HaPlayProjectJsonContext.Default.HaPlayProject);
        var back = System.Text.Json.JsonSerializer.Deserialize(
            json, HaPlayProjectJsonContext.Default.HaPlayProject)!;
        var restored = Assert.IsType<MmdPlaylistItem>(
            Assert.IsType<MediaCueNode>(back.CueLists[0].Nodes[0]).Source);
        Assert.Equal(-22, restored.CameraDistance);
        Assert.Equal("/tmp/dance.vmd", restored.MotionPath);
    }

    [Fact]
    public void CueMapper_MapsYouTubeCue_ToCanonicalUri_WithCaptionSidecarSubtitle()
    {
        var srt = Path.Combine(_dir, "cap.srt");
        File.WriteAllText(srt, "1\n00:00:00,000 --> 00:00:01,000\nhi\n");
        var compositionId = Guid.NewGuid();
        var cueList = new CueList
        {
            Name = "Act",
            Compositions = { new CueComposition { Id = compositionId, Width = 1920, Height = 1080 } },
            Nodes =
            {
                new MediaCueNode
                {
                    Number = "1",
                    Label = "yt",
                    Source = new YouTubePlaylistItem("dQw4w9WgXcQ")
                    {
                        VideoStreamDescriptor = "1080p|avc1|mp4",
                        AudioStreamDescriptor = "opus|webm|en",
                        Subtitles = [new CueSubtitleSelection { Path = srt, Label = "English" }],
                    },
                    Subtitles = [new CueSubtitleSelection { Path = srt, Label = "English" }],
                    VideoPlacements =
                    {
                        new CueVideoPlacement { CompositionId = compositionId },
                    },
                },
            },
        };

        var document = HaPlayShowMapper.ToShowDocument(cueList);
        var clip = Assert.Single(document.Clips);
        Assert.StartsWith("youtube://dQw4w9WgXcQ", clip.MediaPath);
        Assert.True(clip.NotifyNaturalEnd, "a finite cached youtube asset must fire cue auto-follow at EOF");
        var sub = Assert.Single(clip.Subtitles!);
        Assert.Equal(srt, sub.Path);
    }
}
